import type { Localized, Product } from "./types";

/**
 * Viana Pharmacy — full product catalog.
 * Prices in USD. BRL and PYG derive from currency-context rates at display.
 */
function en(value: string): Localized {
  const upper = value.toUpperCase();
  return { es: upper, pt: upper, en: upper };
}

export const products: Product[] = [
  // ── HORMONAS Y PEPTIDOS ─────────────────────────────────────────────
  {
    id: "ztrop-pen-72ui",
    slug: "ztrop-pen-72ui",
    name: en("Ztrop Pen 72IU Liof."),
    desc: en("Lyophilized growth hormone pen (72IU single-dose)."),
    priceUSD: 195,
    category: "hormonas-peptidos",
    image: "ztrop-pen-72ui",
    lab: "ZPHC",
    variantGroup: "ztrop-pen",
    strength: "Pen 72IU liof.",
  },
  {
    id: "ztrop-aq-90ui",
    slug: "ztrop-aq-90ui",
    name: en("Ztrop AQ 90IU"),
    desc: en("Aqueous growth hormone solution (90IU cartridge)."),
    priceUSD: 235,
    category: "hormonas-peptidos",
    image: "ZTROP-AQ-90IU",
    lab: "ZPHC",
    variantGroup: "ztrop-pen",
    strength: "AQ 90IU",
  },
  {
    id: "ztrop-x-80ui",
    slug: "ztrop-x-80ui",
    name: en("Ztrop 80IU"),
    desc: en("Growth hormone vial, 80IU."),
    priceUSD: 215,
    category: "hormonas-peptidos",
    image: "ztrop-x-80ui",
    lab: "ZPHC",
    variantGroup: "ztrop-x",
    strength: "80IU",
  },
  {
    id: "ztrop-x-150ui-diluido",
    slug: "ztrop-x-150ui-diluido",
    name: en("Ztrop 150IU Diluted"),
    desc: en("Diluted growth hormone vial, 150IU."),
    priceUSD: 225,
    category: "hormonas-peptidos",
    image: "ztrop-150ui-premixed",
    lab: "ZPHC",
    variantGroup: "ztrop-x",
    strength: "150IU diluted",
  },
  {
    id: "ztrop-x-200ui",
    slug: "ztrop-x-200ui",
    name: en("Ztrop 200IU"),
    desc: en("Growth hormone vial, 200IU."),
    priceUSD: 405,
    category: "hormonas-peptidos",
    image: "ztrop-200ui",
    lab: "ZPHC",
    featured: true,
    variantGroup: "ztrop-x",
    strength: "200IU",
  },
  {
    id: "ztrop-x-320ui",
    slug: "ztrop-x-320ui",
    name: en("Ztrop 320IU"),
    desc: en("Growth hormone vial, 320IU."),
    priceUSD: 415,
    category: "hormonas-peptidos",
    image: "ztrop-320iu",
    lab: "ZPHC",
    featured: true,
    variantGroup: "ztrop-x",
    strength: "320IU",
  },
  {
    id: "ztrop-144ui-2-refills",
    slug: "ztrop-144ui-2-refills",
    name: en("Ztrop 144IU (2 Refills)"),
    desc: en("Growth hormone recharges: 2 refill cartridges of 72IU."),
    priceUSD: 285,
    category: "hormonas-peptidos",
    image: "ztrop-144ui",
    lab: "ZPHC",
    variantGroup: "ztrop-pen",
    strength: "144IU (2 refills)",
  },
  {
    id: "multi-pen-gh-180ui",
    slug: "multi-pen-gh-180ui",
    name: en("Multi Pen GH 180IU"),
    desc: en("Multi-function growth hormone pen, 180IU."),
    priceUSD: 57.50,
    category: "hormonas-peptidos",
    image: "multi-pen-gh",
    lab: "ZPHC",
  },
  {
    id: "hgh-fragment-5mg",
    slug: "hgh-fragment-5mg",
    name: en("HGH Fragment 5mg (176-191AA)"),
    desc: en("Growth hormone fragment peptide for lipolysis (single 5mg vial)."),
    priceUSD: 63,
    category: "hormonas-peptidos",
    image: "HGH-FRAGMENT-5MG",
    lab: "ZPHC",
    variantGroup: "hgh-fragment",
    strength: "5mg (176-191AA)",
  },
  {
    id: "hgh-fragment-5mg-5",
    slug: "hgh-fragment-5mg-5",
    name: en("HGH Fragment 5mg x5"),
    desc: en("Growth hormone fragment peptide, 5 vials of 5mg."),
    priceUSD: 255,
    category: "hormonas-peptidos",
    image: "HGH-FRAGMENT-5MG",
    lab: "ZPHC",
    variantGroup: "hgh-fragment",
    strength: "5mg (5 vials)",
  },
  {
    id: "hgh-fragment-2-5mg",
    slug: "hgh-fragment-2-5mg",
    name: en("HGH Fragment 2.5mg x5"),
    desc: en("Growth hormone fragment peptide, 5 vials of 2.5mg."),
    priceUSD: 175,
    category: "hormonas-peptidos",
    image: "HGH-FRAGMENT-5MG",
    lab: "ZPHC",
    variantGroup: "hgh-fragment",
    strength: "2.5mg (5 vials)",
  },
  {
    id: "hgh-fragment-10mg",
    slug: "hgh-fragment-10mg",
    name: en("HGH Fragment 10mg x5"),
    desc: en("Growth hormone fragment peptide, 5 vials of 10mg."),
    priceUSD: 305,
    category: "hormonas-peptidos",
    image: "HGH-FRAGMENT-10MG",
    lab: "ZPHC",
    featured: true,
    variantGroup: "hgh-fragment",
    strength: "10mg (5 vials)",
  },
  {
    id: "igf-1-1mg",
    slug: "igf-1-1mg",
    name: en("IGF-1 1mg"),
    desc: en("Insulin-like growth factor, 5 vials of 1mg."),
    priceUSD: 165,
    category: "hormonas-peptidos",
    image: "IGF-1-1MG",
    lab: "ZPHC",
  },
  {
    id: "retatrutida-120mg",
    slug: "retatrutida-120mg",
    name: en("Retatrutide 120mg Diluted"),
    desc: en("GLP-1/GIP/Glucagon analog, high-concentration diluted vial."),
    priceUSD: 325,
    category: "hormonas-peptidos",
    image: "Retratutide-60mg",
    lab: "ZPHC",
    featured: true,
    variantGroup: "retatrutide",
    strength: "120mg diluted",
  },
  {
    id: "retatrutide-pen-60mg",
    slug: "retatrutide-pen-60mg",
    name: en("Retatrutide Pen 60mg"),
    desc: en("GLP-1/GIP/Glucagon analog, pre-filled pen."),
    priceUSD: 275,
    category: "hormonas-peptidos",
    image: "Retratutide-60mg",
    lab: "ZPHC",
    featured: true,
    variantGroup: "retatrutide",
    strength: "Pen 60mg",
  },
  {
    id: "retatrutide-pen-30mg",
    slug: "retatrutide-pen-30mg",
    name: en("Retatrutide Pen 30mg"),
    desc: en("GLP-1/GIP/Glucagon analog, pre-filled pen."),
    priceUSD: 200,
    category: "hormonas-peptidos",
    image: "RETRATUTIDE-30MG",
    lab: "ZPHC",
    variantGroup: "retatrutide",
    strength: "Pen 30mg",
  },
  {
    id: "retatrutide-60mg-5",
    slug: "retatrutide-60mg-5",
    name: en("Retatrutide 60mg x5"),
    desc: en("GLP-1/GIP/Glucagon analog, 5 vials of 60mg."),
    priceUSD: 275,
    category: "hormonas-peptidos",
    image: "Retratutide-60mg",
    lab: "ZPHC",
    variantGroup: "retatrutide",
    strength: "60mg (5 vials)",
  },
  {
    id: "tirzepatida-pen-75mg",
    slug: "tirzepatida-pen-75mg",
    name: en("Tirzepatide Pen 75mg"),
    desc: en("GIP/GLP-1 analog, pre-filled pen."),
    priceUSD: 210,
    category: "hormonas-peptidos",
    image: "tirzepatide-75-pen-box",
    lab: "ZPHC",
    featured: true,
    variantGroup: "tirzepatide",
    strength: "Pen 75mg",
  },
  {
    id: "tirzepatida-pen-30mg",
    slug: "tirzepatida-pen-30mg",
    name: en("Tirzepatide Pen 30mg"),
    desc: en("GIP/GLP-1 analog, pre-filled pen."),
    priceUSD: 160,
    category: "hormonas-peptidos",
    image: "tirzerpatide-15mg",
    lab: "ZPHC",
    variantGroup: "tirzepatide",
    strength: "Pen 30mg",
  },
  {
    id: "tirzepatide-150mg",
    slug: "tirzepatide-150mg",
    name: en("Tirzepatide 150mg"),
    desc: en("GIP/GLP-1 analog, multipack of 5 vials of 30mg (total 150mg)."),
    priceUSD: 265,
    category: "hormonas-peptidos",
    image: "zphc-tizerpatide-150mg",
    lab: "ZPHC",
    variantGroup: "tirzepatide",
    strength: "150mg (5x30mg)",
  },
  {
    id: "tirzepatide-15mg",
    slug: "tirzepatide-15mg",
    name: en("Tirzepatide 15mg"),
    desc: en("GIP/GLP-1 analog vial."),
    priceUSD: 55,
    category: "hormonas-peptidos",
    image: "tizerpatide-15mg-box",
    lab: "ZPHC",
    variantGroup: "tirzepatide",
    strength: "15mg",
  },
  {
    id: "tirzepatide-25mg-amp",
    slug: "tirzepatide-25mg-amp",
    name: en("Tirzepatide 25mg x5"),
    desc: en("GIP/GLP-1 analog, 5 ampoules of 25mg."),
    priceUSD: 105,
    category: "hormonas-peptidos",
    image: "tirzerpatide-25mg",
    lab: "ZPHC",
    variantGroup: "tirzepatide",
    strength: "25mg (5 amp)",
  },
  {
    id: "tirzepatide-50mg-amp",
    slug: "tirzepatide-50mg-amp",
    name: en("Tirzepatide 50mg x5"),
    desc: en("GIP/GLP-1 analog, 5 ampoules of 50mg."),
    priceUSD: 155,
    category: "hormonas-peptidos",
    image: "tirzerpatide-50mg",
    lab: "ZPHC",
    variantGroup: "tirzepatide",
    strength: "50mg (5 amp)",
  },
  {
    id: "semaglutida-pen",
    slug: "semaglutida-pen",
    name: en("Semaglutide Pen 6mg"),
    desc: en("GLP-1 analog, pre-filled pen."),
    priceUSD: 115,
    category: "hormonas-peptidos",
    image: "semaglutide-pen-6mg",
    lab: "ZPHC",
  },
  {
    id: "hcg-5000ui",
    slug: "hcg-5000ui",
    name: en("HCG 5000IU"),
    desc: en("Human chorionic gonadotropin, 5 ampoules of 5000IU."),
    priceUSD: 45,
    category: "hormonas-peptidos",
    image: "HCG-5000IU",
    lab: "ZPHC",
  },
  {
    id: "melanotan-2-pen",
    slug: "melanotan-2-pen",
    name: en("Melanotan 2 Pen 30mg"),
    desc: en("Melanocyte-stimulating hormone analog, pre-filled pen."),
    priceUSD: 95,
    category: "hormonas-peptidos",
    image: "melanotan-2-30mg",
    lab: "ZPHC",
    variantGroup: "melanotan-2",
    strength: "Pen 30mg",
  },
  {
    id: "melanotan-2-10mg",
    slug: "melanotan-2-10mg",
    name: en("Melanotan-2 10mg"),
    desc: en("Melanocyte-stimulating hormone analog, 10mg vial."),
    priceUSD: 55,
    category: "hormonas-peptidos",
    image: "melanotan-2-10mg",
    lab: "ZPHC",
    variantGroup: "melanotan-2",
    strength: "10mg",
  },

  // ── ESTEROIDES ANABOLICOS ────────────────────────────────────────────
  {
    id: "testosterone-suspension",
    slug: "testosterone-suspension",
    name: en("Testosterone Suspension AQ 100mg"),
    desc: en("Aqueous testosterone suspension, fast-acting injectable."),
    priceUSD: 47,
    category: "esteroides-anabolicos",
    image: "testosterone-aq-100mg",
    lab: "ZPHC",
  },
  {
    id: "testosterone-undecanoato",
    slug: "testosterone-undecanoato",
    name: en("Testosterone Undecanoate 250mg"),
    desc: en("Long-acting testosterone injectable solution."),
    priceUSD: 53,
    category: "esteroides-anabolicos",
    image: "testosterone-undecaonate-250mg",
    lab: "ZPHC",
  },
  {
    id: "testosterone-propionato",
    slug: "testosterone-propionato",
    name: en("Testosterone Propionate 100mg"),
    desc: en("Fast-acting testosterone injectable solution."),
    priceUSD: 42,
    category: "esteroides-anabolicos",
    image: "propionato-testo-100mg",
    lab: "ZPHC",
  },
  {
    id: "test-enantato-400",
    slug: "test-enantato-400",
    name: en("Testosterone Enanthate 400 10ml"),
    desc: en("Testosterone enanthate 400mg/ml vial, 10ml."),
    priceUSD: 55,
    category: "esteroides-anabolicos",
    image: "testosterone-enanthate-10ml",
    lab: "ZPHC",
  },
  {
    id: "testosterone-cypionate",
    slug: "testosterone-cypionate",
    name: en("Testosterone Cypionate 250mg"),
    desc: en("Testosterone cypionate injectable solution."),
    priceUSD: 45,
    category: "esteroides-anabolicos",
    image: "testo-cyphionate-250mg",
    lab: "ZPHC",
  },
  {
    id: "trembo-hexa-100mg",
    slug: "trembo-hexa-100mg",
    name: en("Trembo Hexa 100mg"),
    desc: en("Trenbolone hexahydrobenzylcarbonate injectable."),
    priceUSD: 70,
    category: "esteroides-anabolicos",
    image: "trenbolone-hexa",
    lab: "ZPHC",
    variantGroup: "trembo-hexa",
    strength: "100mg",
  },
  {
    id: "trembo-hexa-10ml",
    slug: "trembo-hexa-10ml",
    name: en("Trembo Hexa 100mg 10ml"),
    desc: en("Trenbolone hexahydrobenzylcarbonate injectable, 10ml vial."),
    priceUSD: 70,
    category: "esteroides-anabolicos",
    image: "trenbolone-hexa",
    lab: "ZPHC",
    variantGroup: "trembo-hexa",
    strength: "100mg 10ml",
  },
  {
    id: "trembo-enantato",
    slug: "trembo-enantato",
    name: en("Trembo Enanthate 200mg"),
    desc: en("Trenbolone enanthate injectable solution."),
    priceUSD: 63,
    category: "esteroides-anabolicos",
    image: "trembo-enantato-200mg",
    lab: "ZPHC",
  },
  {
    id: "trestolone-acetato-25mg",
    slug: "trestolone-acetato-25mg",
    name: en("Trestolone Acetate 25mg"),
    desc: en("Trestolone acetate injectable solution, 10ml vial."),
    priceUSD: 57,
    category: "esteroides-anabolicos",
    image: "trestrolone-acetato-50mg",
    lab: "ZPHC",
    variantGroup: "trestolone-acetate",
    strength: "25mg 10ml",
  },
  {
    id: "trestolone-enantato-50mg",
    slug: "trestolone-enantato-50mg",
    name: en("Trestolone Enanthate 50mg"),
    desc: en("Trestolone enanthate injectable solution."),
    priceUSD: 85,
    category: "esteroides-anabolicos",
    image: "trestolone-enanthate-50mg",
    lab: "ZPHC",
    variantGroup: "trestolone-enanthate",
    strength: "50mg",
  },
  {
    id: "trestolone-enantato-100mg",
    slug: "trestolone-enantato-100mg",
    name: en("Trestolone Enanthate 100mg"),
    desc: en("Trestolone enanthate injectable solution."),
    priceUSD: 105,
    category: "esteroides-anabolicos",
    image: "trestolone-enanthate-100mg",
    lab: "ZPHC",
    variantGroup: "trestolone-enanthate",
    strength: "100mg",
  },
  {
    id: "stano-susp-50mg",
    slug: "stano-susp-50mg",
    name: en("Stanozolol Suspension 50mg"),
    desc: en("Stanozolol aqueous suspension injectable."),
    priceUSD: 43,
    category: "esteroides-anabolicos",
    image: "stano-susp-50mg",
    lab: "ZPHC",
  },
  {
    id: "fluoxymesterolona",
    slug: "fluoxymesterolona",
    name: en("Fluoxymesterolone"),
    desc: en("Oral anabolic steroid, 100 tablets per bottle."),
    priceUSD: 80,
    category: "esteroides-anabolicos",
    image: "fluoxymesterone",
    lab: "ZPHC",
  },
  {
    id: "methandione",
    slug: "methandione",
    name: en("Methandione"),
    desc: en("Oral methandienone, 100 tablets per bottle."),
    priceUSD: 47.80,
    category: "esteroides-anabolicos",
    image: "methandione",
    lab: "ZPHC",
  },
  {
    id: "super-mix",
    slug: "super-mix",
    name: en("Super Mix 250mg"),
    desc: en("Multi-component steroid blend, 250mg/ml injectable."),
    priceUSD: 65,
    category: "esteroides-anabolicos",
    image: "super-mix-250mg",
    lab: "ZPHC",
  },
  {
    id: "mega-mix",
    slug: "mega-mix",
    name: en("Mega Mix 250mg"),
    desc: en("Multi-component steroid blend, 250mg/ml injectable."),
    priceUSD: 63,
    category: "esteroides-anabolicos",
    image: "megamix-250mg",
    lab: "ZPHC",
  },
  {
    id: "mega-mass-mix",
    slug: "mega-mass-mix",
    name: en("Mega Mass Mix 50mg"),
    desc: en("Mass-building steroid blend, 50mg vial."),
    priceUSD: 175,
    category: "esteroides-anabolicos",
    image: "mega-mass-mix-50mg",
    lab: "ZPHC",
  },

  // ── MODULADORES HORMONALES ───────────────────────────────────────────
  {
    id: "tamoxifeno",
    slug: "tamoxifeno",
    name: en("Tamoxifen Citrate 20mg"),
    desc: en("Selective estrogen receptor modulator (SERM), 100 capsules per bottle."),
    priceUSD: 50,
    category: "moduladores-hormonales",
    image: "Tamoxifen-Citrate-20mg",
    lab: "ZPHC",
  },
  {
    id: "anastrozol",
    slug: "anastrozol",
    name: en("Anastrozole 1mg"),
    desc: en("Aromatase inhibitor, 100 capsules per bottle."),
    priceUSD: 56,
    category: "moduladores-hormonales",
    image: "anastrozol-1mg",
    lab: "ZPHC",
  },
  {
    id: "cabergoline",
    slug: "cabergoline",
    name: en("Cabergoline 0.25mg"),
    desc: en("Prolactin inhibitor tablets."),
    priceUSD: 80,
    category: "moduladores-hormonales",
    image: "caber-goline-0-25",
    lab: "ZPHC",
  },

  // ── METABOLICOS Y QUEMAGRASAS ────────────────────────────────────────
  {
    id: "aod-9604-12mg",
    slug: "aod-9604-12mg",
    name: en("AOD-9604 12.5mg"),
    desc: en("Modified HGH fragment peptide for lipolysis, 12.5mg vial."),
    priceUSD: 180,
    category: "metabolicos-quemagrasas",
    image: "AOD9604-12-5",
    lab: "ZPHC",
    variantGroup: "aod9604",
    strength: "12.5mg",
  },
  {
    id: "aod-9604-25mg",
    slug: "aod-9604-25mg",
    name: en("AOD-9604 25mg"),
    desc: en("Modified HGH fragment peptide for lipolysis, 25mg vial."),
    priceUSD: 225,
    category: "metabolicos-quemagrasas",
    image: "AOD9604",
    lab: "ZPHC",
    variantGroup: "aod9604",
    strength: "25mg",
  },
  {
    id: "clenbuterol",
    slug: "clenbuterol",
    name: en("Clenbuterol 40mcg"),
    desc: en("Bronchodilator and thermogenic, 100 tablets per bottle."),
    priceUSD: 39,
    category: "metabolicos-quemagrasas",
    image: "clembuterol-40mcg",
    lab: "ZPHC",
  },
  {
    id: "cyt3",
    slug: "cyt3",
    name: en("Cyt3 6mg"),
    desc: en("Thermogenic agent, 100 tablets per bottle."),
    priceUSD: 55,
    category: "metabolicos-quemagrasas",
    image: "CYT3-6MG",
    lab: "ZPHC",
  },
  {
    id: "super-slim-27mg",
    slug: "super-slim-27mg",
    name: en("Super Slim Mix 27.5mg"),
    desc: en("Fat-burner peptide blend, 27.5mg vial."),
    priceUSD: 235,
    category: "metabolicos-quemagrasas",
    image: "super-slim-mix-27-5-mg",
    lab: "ZPHC",
    variantGroup: "super-slim",
    strength: "27.5mg",
  },
  {
    id: "super-slim-55mg",
    slug: "super-slim-55mg",
    name: en("Super Slim Mix 55mg"),
    desc: en("Fat-burner peptide blend, 55mg vial."),
    priceUSD: 315,
    category: "metabolicos-quemagrasas",
    image: "super-slim-mix-55mg",
    lab: "ZPHC",
    variantGroup: "super-slim",
    strength: "55mg",
  },
  {
    id: "double-burn",
    slug: "double-burn",
    name: en("Double Burn Mix 25mg"),
    desc: en("Dual thermogenic blend, 25mg vial."),
    priceUSD: 205,
    category: "metabolicos-quemagrasas",
    image: "double-burn-mix-25mg",
    lab: "ZPHC",
  },
  {
    id: "synthol-seo",
    slug: "synthol-seo",
    name: en("Synthol SEO 40ml"),
    desc: en("Sterile oil for localized muscle enhancement, 40ml."),
    priceUSD: 55,
    category: "metabolicos-quemagrasas",
    image: "synthol-40ml",
    lab: "ZPHC",
  },

  // ── REGENERACION Y REPARACION ────────────────────────────────────────
  {
    id: "bpc-157-20mg",
    slug: "bpc-157-20mg",
    name: en("BPC-157 20mg"),
    desc: en("Gut and tendon repair peptide, 20mg vial."),
    priceUSD: 95,
    category: "regeneracion-reparacion",
    image: "bpc-157-20mg",
    lab: "ZPHC",
    featured: true,
    variantGroup: "bpc157",
    strength: "20mg",
  },
  {
    id: "bpc-157-25mg",
    slug: "bpc-157-25mg",
    name: en("BPC-157 25mg x5"),
    desc: en("Repair peptide, 5 vials of 25mg."),
    priceUSD: 105,
    category: "regeneracion-reparacion",
    image: "BPC-157-25MG",
    lab: "ZPHC",
    variantGroup: "bpc157",
    strength: "25mg (5 vials)",
  },
  {
    id: "tb-500-20mg",
    slug: "tb-500-20mg",
    name: en("TB-500 20mg"),
    desc: en("Tissue repair peptide, 20mg vial."),
    priceUSD: 100,
    category: "regeneracion-reparacion",
    image: "tb-500-20mg",
    lab: "ZPHC",
    variantGroup: "tb500",
    strength: "20mg",
  },
  {
    id: "tb-500-25mg",
    slug: "tb-500-25mg",
    name: en("TB-500 25mg x5"),
    desc: en("Tissue repair peptide, 5 vials of 25mg."),
    priceUSD: 155,
    category: "regeneracion-reparacion",
    image: "tb-500-25mg",
    lab: "ZPHC",
    variantGroup: "tb500",
    strength: "25mg (5 vials)",
  },
  {
    id: "ghk-cu-60mg",
    slug: "ghk-cu-60mg",
    name: en("GHK-Cu 60mg"),
    desc: en("Copper peptide for skin regeneration, 60mg vial."),
    priceUSD: 155,
    category: "regeneracion-reparacion",
    image: "ghkcu-60mg",
    lab: "ZPHC",
    variantGroup: "ghk-cu",
    strength: "60mg",
  },
  {
    id: "ghk-cu-50mg",
    slug: "ghk-cu-50mg",
    name: en("GHK-Cu 50mg x5"),
    desc: en("Copper peptide, 5 vials of 50mg."),
    priceUSD: 205,
    category: "regeneracion-reparacion",
    image: "GHK-CU-50MG",
    lab: "ZPHC",
    variantGroup: "ghk-cu",
    strength: "50mg (5 vials)",
  },
  {
    id: "ghk-cu-200mg",
    slug: "ghk-cu-200mg",
    name: en("GHK-Cu 200mg"),
    desc: en("Copper peptide, high-concentration 200mg vial."),
    priceUSD: 265,
    category: "regeneracion-reparacion",
    image: "GHK-CU-200MG",
    lab: "ZPHC",
    variantGroup: "ghk-cu",
    strength: "200mg",
  },
  {
    id: "ll37",
    slug: "ll37",
    name: en("LL-37 25mg"),
    desc: en("Antimicrobial and immune-modulating peptide, 25mg vial."),
    priceUSD: 220,
    category: "regeneracion-reparacion",
    image: "LL37-25MG",
    lab: "ZPHC",
  },
  {
    id: "ultra-rehab-50mg",
    slug: "ultra-rehab-50mg",
    name: en("Ultra Rehab Mix 50mg"),
    desc: en("Regenerative peptide blend, 50mg vial."),
    priceUSD: 185,
    category: "regeneracion-reparacion",
    image: "ultra-rehab-mix-50mg",
    lab: "ZPHC",
    variantGroup: "ultra-rehab",
    strength: "50mg",
  },
  {
    id: "ultra-rehab-20mg",
    slug: "ultra-rehab-20mg",
    name: en("Ultra Rehab Mix 20mg"),
    desc: en("Regenerative peptide blend, 20mg vial."),
    priceUSD: 150,
    category: "regeneracion-reparacion",
    image: "ultra-rehab-mix-20mg",
    lab: "ZPHC",
    variantGroup: "ultra-rehab",
    strength: "20mg",
  },
  {
    id: "ipamorelin",
    slug: "ipamorelin",
    name: en("Ipamorelin 25mg"),
    desc: en("Growth-hormone-releasing peptide, 25mg vial."),
    priceUSD: 115,
    category: "regeneracion-reparacion",
    image: "IPAMORELIN-25MG",
    lab: "ZPHC",
  },
  {
    id: "ghrp-2",
    slug: "ghrp-2",
    name: en("GHRP-2 25mg x5"),
    desc: en("Growth-hormone-releasing peptide, 5 vials of 25mg."),
    priceUSD: 95,
    category: "regeneracion-reparacion",
    image: "gphr-2-25mg",
    lab: "ZPHC",
  },
  {
    id: "ghrp-6",
    slug: "ghrp-6",
    name: en("GHRP-6 25mg x5"),
    desc: en("Growth-hormone-releasing peptide, 5 vials of 25mg."),
    priceUSD: 95,
    category: "regeneracion-reparacion",
    image: "ghrp-6",
    lab: "ZPHC",
  },
  {
    id: "mots-c",
    slug: "mots-c",
    name: en("MOTS-C 20mg"),
    desc: en("Mitochondrial-derived peptide, 20mg vial."),
    priceUSD: 185,
    category: "regeneracion-reparacion",
    image: "mots-c-20mg",
    lab: "ZPHC",
  },

  // ── BIENESTAR Y ANTIENVEJECIMIENTO ───────────────────────────────────
  {
    id: "nad-1000mg",
    slug: "nad-1000mg",
    name: en("NAD+ 1000mg"),
    desc: en("Nicotinamide adenine dinucleotide vial."),
    priceUSD: 85,
    category: "bienestar-antienvejecimiento",
    image: "NAD+1000MG",
    lab: "ZPHC",
    variantGroup: "nad",
    strength: "1000mg",
  },
  {
    id: "nad-2500mg",
    slug: "nad-2500mg",
    name: en("NAD+ 2500mg"),
    desc: en("Nicotinamide adenine dinucleotide, 2500mg vial."),
    priceUSD: 165,
    category: "bienestar-antienvejecimiento",
    image: "NAD+2500MG",
    lab: "ZPHC",
    variantGroup: "nad",
    strength: "2500mg",
  },
  {
    id: "nad-pen-aquoso",
    slug: "nad-pen-aquoso",
    name: en("NAD+ 1000mg Aqueous Pen"),
    desc: en("NAD+ in an aqueous pen, 1000mg."),
    priceUSD: 105,
    category: "bienestar-antienvejecimiento",
    image: "nad+1000mg-aquoso",
    lab: "ZPHC",
    variantGroup: "nad",
    strength: "1000mg Aqueous Pen",
  },
  {
    id: "glutathione",
    slug: "glutathione",
    name: en("L-Glutathione 3000mg"),
    desc: en("Master antioxidant, 3000mg vial."),
    priceUSD: 105,
    category: "bienestar-antienvejecimiento",
    image: "gluthatione-3000mg",
    lab: "ZPHC",
  },
  {
    id: "epitalon-100mg",
    slug: "epitalon-100mg",
    name: en("Epitalon 100mg"),
    desc: en("Telomerase-activating anti-aging peptide, 100mg vial."),
    priceUSD: 185,
    category: "bienestar-antienvejecimiento",
    image: "Ephitalon-100mg",
    lab: "ZPHC",
    variantGroup: "epitalon",
    strength: "100mg",
  },
  {
    id: "epitalon-50mg",
    slug: "epitalon-50mg",
    name: en("Epitalon 50mg"),
    desc: en("Anti-aging peptide, 50mg vial."),
    priceUSD: 110,
    category: "bienestar-antienvejecimiento",
    image: "ephitalon-50mg",
    lab: "ZPHC",
    variantGroup: "epitalon",
    strength: "50mg",
  },
  {
    id: "glow-pro-mix",
    slug: "glow-pro-mix",
    name: en("Glow Pro Mix 60mg"),
    desc: en("Skin and regeneration peptide blend, 60mg vial."),
    priceUSD: 185,
    category: "bienestar-antienvejecimiento",
    image: "glow-pro-mix-60mg",
    lab: "ZPHC",
  },
  {
    id: "wellness-mix",
    slug: "wellness-mix",
    name: en("Wellness Mix 25mg"),
    desc: en("Wellness and regeneration blend, 25mg vial."),
    priceUSD: 175,
    category: "bienestar-antienvejecimiento",
    image: "wellness-mix-25mg",
    lab: "ZPHC",
  },
];

export const productById = (id: string): Product | undefined =>
  products.find((p) => p.id === id);

export const productBySlug = (slug: string): Product | undefined =>
  products.find((p) => p.slug === slug);

export const featuredProducts = (): Product[] =>
  products.filter((p) => p.featured);

export const productsByCategory = (categoryId: string): Product[] =>
  products.filter((p) => p.category === categoryId);

export const offerProducts = (): Product[] =>
  products.filter((p) => typeof p.oldPriceUSD === "number");

export const nameOf = (p: Product, lang: keyof Product["name"]): string =>
  p.name[lang];

export const descOf = (p: Product, lang: keyof Product["desc"]): string =>
  p.desc[lang];
